services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
  backend:
    build: ./backend
    entrypoint: ["/app/entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - "3008:3000"
    env_file: .env
