  [31morigin/Dev[m
  [31morigin/Development[m
  [31morigin/HEAD[m -> origin/main
  [31morigin/codex/add-aesthetic-category-to-components-popup[m
  [31morigin/codex/add-architecture-section-to-readme.md[m
  [31morigin/codex/add-architecture-section-to-readme.md-3o8lt2[m
  [31morigin/codex/add-back-button-and-reset-dirty-state[m
  [31morigin/codex/add-component-sidebar-and-toolbar[m
  [31morigin/codex/add-component-sidebar-and-toolbar-cj24lm[m
  [31morigin/codex/add-component-sidebar-and-toolbar-jgplmn[m
  [31morigin/codex/add-component-sidebar-and-toolbar-lov1vp[m
  [31morigin/codex/add-cors-support-for-development-frontend[m
  [31morigin/codex/add-crud-functionality-for-sections[m
  [31morigin/codex/add-dependencies-installation-to-dockerfile[m
  [31morigin/codex/add-deployment-and-startup-instructions[m
  [31morigin/codex/add-entrypoint-script-for-backend-service[m
  [31morigin/codex/add-fallback-icons-for-legajos-menu[m
  [31morigin/codex/add-fallback-icons-for-legajos-menu-03kouz[m
  [31morigin/codex/add-fallback-icons-for-legajos-menu-h8z2q8[m
  [31morigin/codex/add-fallback-icons-for-legajos-menu-x44xyy[m
  [31morigin/codex/add-fixed-lucide-react-dependency-and-update-sidenav[m
  [31morigin/codex/add-form-layout-persistence-in-django[m
  [31morigin/codex/add-framer-motion-and-animate-sidenav[m
  [31morigin/codex/add-gunicorn-to-backend-requirements[m
  [31morigin/codex/add-jwt-authentication-for-django-users[m
  [31morigin/codex/add-jwt-authentication-with-simple-jwt[m
  [31morigin/codex/add-mobile-overlay-for-side-menu[m
  [31morigin/codex/add-next_public_api_url-to-.env.example[m
  [31morigin/codex/add-pkg-config-to-dockerfile-installation[m
  [31morigin/codex/add-support-for-sections-and-repeatable-lists[m
  [31morigin/codex/add-tecnologias-section-to-readme[m
  [31morigin/codex/add-tests-and-documentation-for-module[m
  [31morigin/codex/add-tests-for-/api/plantillas/id/layout-endpoint[m
  [31morigin/codex/add-useeffect-for-body-overflow-class[m
  [31morigin/codex/add-validations-and-serialization-for-templates[m
  [31morigin/codex/add-visual-blocks-in-popup-with-grid-support[m
  [31morigin/codex/add-visual-configuration-to-templates[m
  [31morigin/codex/add-visual-tab-to-template-builder[m
  [31morigin/codex/ajustar-menu-superior-junto-al-menu-izquierdo[m
  [31morigin/codex/always-show-sidebar-and-top-menu[m
  [31morigin/codex/annotate-type-in-page.tsx-map-function[m
  [31morigin/codex/apply-design-from-plantillas-to-legajos-table[m
  [31morigin/codex/convert-page-to-client-component[m
  [31morigin/codex/create-api-client-and-layout-types[m
  [31morigin/codex/create-backend-dockerfile-and-service[m
  [31morigin/codex/create-backend-structure-and-setup[m
  [31morigin/codex/create-dockerfile-for-frontend-service[m
  [31morigin/codex/create-readme.md-and-environment-files[m
  [31morigin/codex/create-responsive-global-layout-for-nodo-app[m
  [31morigin/codex/create-visual-editor-skeleton[m
  [31morigin/codex/develop-dynamic-template-builder-feature[m
  [31morigin/codex/develop-legajo-and-plantilla-modules[m
  [31morigin/codex/develop-legajo-and-plantilla-modules-158138[m
  [31morigin/codex/develop-legajo-and-plantilla-modules-2b0voy[m
  [31morigin/codex/develop-legajo-and-plantilla-modules-var2ng[m
  [31morigin/codex/develop-legajo-templates-module[m
  [31morigin/codex/develop-legajo-templates-module-zt30o1[m
  [31morigin/codex/enable-drag-and-drop-for-grid-layout[m
  [31morigin/codex/fix-500-error-with-trailing-slash-in-post[m
  [31morigin/codex/fix-backend-entrypoint-script-error[m
  [31morigin/codex/fix-button-export-and-legajosmenu-errors[m
  [31morigin/codex/fix-button-export-and-legajosmenu-errors-l2ddci[m
  [31morigin/codex/fix-button-export-and-legajosmenu-errors-m3lc0w[m
  [31morigin/codex/fix-button-export-and-legajosmenu-errors-pwezpa[m
  [31morigin/codex/fix-dns-error-for-backend-calls[m
  [31morigin/codex/fix-docker-build-failure-and-sync-dependencies[m
  [31morigin/codex/fix-drag-and-drop-ordering-in-templates[m
  [31morigin/codex/fix-duplicate-route-paths-error[m
  [31morigin/codex/fix-frontend-build-with-framer-motion[m
  [31morigin/codex/fix-login-to-use-auth_user-table[m
  [31morigin/codex/fix-login-url-for-browser-and-ssr[m
  [31morigin/codex/fix-modal-section-insertion-bug[m
  [31morigin/codex/fix-navigation-errors-and-update-sidenav[m
  [31morigin/codex/fix-next-ssr-proxy-and-authentication-issues[m
  [31morigin/codex/fix-next-ssr-proxy-and-authentication-issues-e257q8[m
  [31morigin/codex/fix-next.js-404-error-for-api-calls[m
  [31morigin/codex/fix-unauthorized-errors-for-api-requests[m
  [31morigin/codex/fix-undefined-component-error-in-legajosmenu[m
  [31morigin/codex/hide-menu-in-login-page[m
  [31morigin/codex/implement-drag-and-drop-enhancements[m
  [31morigin/codex/implement-drag-and-drop-functionality[m
  [31morigin/codex/implement-editable-properties-for-selected-fields[m
  [31morigin/codex/implement-editor-changes-persistence[m
  [31morigin/codex/implement-legajos-functionality-in-next.js[m
  [31morigin/codex/implement-session-close-button-logic[m
  [31morigin/codex/implement-user-preview-for-form[m
  [31morigin/codex/implementar-builder-de-legajos-con-drag-and-drop[m
  [31morigin/codex/implementar-cambios-en-el-builder[m
  [31morigin/codex/implementar-drag-drop-en-constructor-de-plantillas[m
  [31morigin/codex/implementar-drag-drop-en-constructor-de-plantillas-hf2qe4[m
  [31morigin/codex/implementar-flujo-de-creacion-de-plantillas[m
  [31morigin/codex/implementar-lista-y-alta-de-legajos-por-plantilla[m
  [31morigin/codex/implementar-login-sin-errores-de-fetch[m
  [31morigin/codex/implementar-rediseno-de-plantilla[m
  [31morigin/codex/improve-a11y-and-ux-for-builder[m
  [31morigin/codex/improve-apifetch-error-handling[m
  [31morigin/codex/improve-dark-mode-styling[m
  [31morigin/codex/integrate-dynamic-preview-and-properties-panel[m
  [31morigin/codex/investigate-template-object-not-saving[m
  [31morigin/codex/migrate-frontend-api-calls-to-use-helpers[m
  [31morigin/codex/normalize-frontend-login-for-next.js[m
  [31morigin/codex/redirect-to-login-on-app-access[m
  [31morigin/codex/refactorizar-sidenav-para-usar-iconos-lucide[m
  [31morigin/codex/regenerate-and-commit-package-lock.json[m
  [31morigin/codex/remove-.env-from-git-history[m
  [31morigin/codex/remove-mysql_user-and-mysql_password-from-docker-compose.yml[m
  [31morigin/codex/remove-version-from-docker-compose.yml[m
  [31morigin/codex/remove-version-from-docker-compose.yml-hwezm2[m
  [31morigin/codex/renderizar-formularios-desde-formlayout[m
  [31morigin/codex/replace-in-memory-filtering-with-database-queries[m
  [31morigin/codex/resolve-/plantillas-implementation-conflict[m
  [31morigin/codex/resolve-/plantillas-implementation-conflict-ylx77h[m
  [31morigin/codex/restore-folder-icon-in-legajos[m
  [31morigin/codex/set-up-frontend-project-structure[m
  [31morigin/codex/set-up-project-folder-structure[m
  [31morigin/codex/setup-docker-with-mysql,-django,-and-next.js[m
  [31morigin/codex/update-backend-settings-for-new-url[m
  [31morigin/codex/update-django-settings-for-environment-variables[m
  [31morigin/codex/update-docker-compose.yml-for-frontend-service[m
  [31morigin/codex/update-docker-compose.yml-mysql-port[m
  [31morigin/codex/update-docker-setup-instructions[m
  [31morigin/codex/update-next_public_api_url-in-.env[m
  [31morigin/codex/update-next_public_api_url-in-.env-5eqt1i[m
  [31morigin/codex/update-next_public_api_url-in-.env-ayfq3x[m
  [31morigin/codex/update-package-lock.json-with-new-dependencies[m
  [31morigin/codex/update-ports-in-docker-compose.yml[m
  [31morigin/codex/update-readme.md-with-setup-instructions[m
  [31morigin/codex/update-sidenav-and-activelink-components[m
  [31morigin/codex/update-sidenav-and-activelink-components-kk8rex[m
  [31morigin/codex/verify-entrypoint-script-and-update-docker-compose[m
  [31morigin/development[m
  [31morigin/main[m
  [31morigin/revert-85-codex/add-fixed-lucide-react-dependency-and-update-sidenav[m
