# Generated by Django 5.2.7 on 2025-10-13 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flujo",
            index=models.Index(
                fields=["is_active", "status", "created_by"],
                name="flows_flujo_is_acti_6c269e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flujo",
            index=models.Index(
                fields=["-updated_at"], name="flows_flujo_updated_4e34fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flujo",
            index=models.Index(fields=["slug"], name="flows_flujo_slug_9b44c8_idx"),
        ),
        migrations.AddIndex(
            model_name="instancelog",
            index=models.Index(
                fields=["instance", "-timestamp"], name="flows_insta_instanc_9b0a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instancelog",
            index=models.Index(
                fields=["level", "-timestamp"], name="flows_insta_level_8878ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instanciaflujo",
            index=models.Index(
                fields=["flow", "status", "created_by"],
                name="flows_insta_flow_id_192d11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instanciaflujo",
            index=models.Index(
                fields=["legajo_id", "status"], name="flows_insta_legajo__5ec3b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instanciaflujo",
            index=models.Index(
                fields=["-started_at"], name="flows_insta_started_b73678_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instanciaflujo",
            index=models.Index(
                fields=["resume_at"], name="flows_insta_resume__55acec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="step",
            index=models.Index(
                fields=["flow", "order"], name="flows_step_flow_id_204d6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="step",
            index=models.Index(
                fields=["step_type"], name="flows_step_step_ty_c8ad8a_idx"
            ),
        ),
    ]
