# Generated by Django 5.2.6 on 2025-09-18 19:15

import django.db.models.functions.text
import plantillas.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('schema', models.JSONField()),
                ('visual_config', models.JSONField(blank=True, default=plantillas.models.default_json)),
                ('layout_json', models.JSONField(blank=True, default=plantillas.models.default_json)),
                ('layout_version', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_plantilla_nombre_ci')],
            },
        ),
    ]
