# Generated by Django 5.2.7 on 2025-10-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="plantilla",
            index=models.Index(
                fields=["estado", "-updated_at"], name="plantillas__estado_a262dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantilla",
            index=models.Index(
                fields=["-updated_at"], name="plantillas__updated_ef5853_idx"
            ),
        ),
    ]
