# Generated by Django 5.2.6 on 2025-09-18 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('grid_values', models.JSONField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, db_index=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legajos', to='plantillas.plantilla')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
