# Generated by Django 5.2.7 on 2025-10-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0001_initial"),
        ("plantillas", "0002_plantilla_plantillas__estado_a262dc_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="legajo",
            index=models.Index(
                fields=["plantilla", "-created_at"],
                name="legajos_leg_plantil_f94392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legajo",
            index=models.Index(
                fields=["-created_at"], name="legajos_leg_created_64bf30_idx"
            ),
        ),
    ]
