# Generated by Django 5.2.9 on 2026-01-08 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0002_legajo_legajos_leg_plantil_f94392_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegajoRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relation_type", models.CharField(max_length=100)),
                ("inverse_relation_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="legajos.legajo",
                    ),
                ),
                (
                    "target_legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="legajos.legajo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_legajo", "relation_type"],
                        name="legajos_leg_source__5d8716_idx",
                    ),
                    models.Index(
                        fields=["target_legajo", "inverse_relation_type"],
                        name="legajos_leg_target__44ce5c_idx",
                    ),
                ],
                "unique_together": {
                    ("source_legajo", "target_legajo", "relation_type")
                },
            },
        ),
    ]
